name: Hourly Air Quality Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-pull-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Python Scripts
        env:
          # Existing Secrets
          PURPLE_AIR_API_KEY: ${{ secrets.PURPLE_AIR_API_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
          # New Secrets to Add
          QUANTAQ_API_KEY: ${{ secrets.QUANTAQ_API_KEY }}
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
        run: |
          python pa_live_pull.py
          python quantaq_pull.py
          python c12_pull.py

